export enum ApiErrors {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",

  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",

  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",

  UNAUTHORIZED = "Unauthorized",
}
