export enum KimikastQueryKeys {
  AUTH = "AUTH",
  LOGOUT = "LOGOUT",
  USER = "USER",
  LISTS = "LISTS",
  LIST = "LIST",
  PUBLIC_USER = "PUBLIC_USER",
  COMMENTS = "COMMENTS",
  CHANGE_USERNAME = "CHANGE_USERNAME",
  PROGRESS = "PROGRESS",
}
